export const poolData = [
  {
    id: 1,
    icon: '/static/images/pool/weth.png',
    title: 'WETH Pool',
    myStake: '0 WETH',
    myRewards: '0 DBP',
    totalStaked: '823.188 WETH',
    apr: 'N/A%',
    walletBalance: '0 WETH',
  },
  {
    id: 2,
    icon: '/static/images/pool/wbtc.png',
    title: 'WBTC Pool',
    myStake: '0 WBTC',
    myRewards: '0 DBP',
    totalStaked: '12.261 WBTC',
    apr: 'N/A%',
    walletBalance: '0 WBTC',
  },
  {
    id: 3,
    icon: '/static/images/pool/usdt.png',
    title: 'USDT Pool',
    myStake: '0 USDT',
    myRewards: '0 DBP',
    totalStaked: '9702.008 USDT',
    apr: 'N/A%',
    walletBalance: '0 USDT',
  },
  {
    id: 4,
    icon: '/static/images/pool/usdc.png',
    title: 'USDC Pool',
    myStake: '0 USDC',
    myRewards: '0 DBP',
    totalStaked: '2257.872 USDC',
    apr: 'N/A%',
    walletBalance: '0 USDC',
  },
  {
    id: 5,
    icon: '/static/images/pool/ocean.png',
    title: 'OCEAN Pool',
    myStake: '0 OCEAN',
    myRewards: '0 DBP',
    totalStaked: '458197.144 OCEAN',
    apr: 'N/A%',
    walletBalance: '0 OCEAN',
  },
  {
    id: 6,
    icon: '/static/images/pool/link.png',
    title: 'LINK Pool',
    myStake: '0 LINK',
    myRewards: '0 DBP',
    totalStaked: '2013.835 LINK',
    apr: 'N/A%',
    walletBalance: '0 LINK',
  },
  {
    id: 7,
    icon: '/static/images/pool/sushi.png',
    title: 'SUSHI Pool',
    myStake: '0 SUSHI',
    myRewards: '0 DBP',
    totalStaked: '30880.990 SUSHI',
    apr: 'N/A%',
    walletBalance: '0 SUSHI',
  },
  {
    id: 8,
    icon: '/static/images/pool/uni.png',
    title: 'UNI Pool',
    myStake: '0 UNI',
    myRewards: '0 DBP',
    totalStaked: '11369.942 UNI',
    apr: 'N/A%',
    walletBalance: '0 UNI',
  },
  {
    id: 9,
    icon: '/static/images/pool/yfi.png',
    title: 'YFI Pool',
    myStake: '0 YFI',
    myRewards: '0 DBP',
    totalStaked: '1.589 YFI',
    apr: 'N/A%',
    walletBalance: '0 YFI',
  },
  {
    id: 10,
    icon: '/static/images/pool/aave.png',
    title: 'AAVE Pool',
    myStake: '0 AAVE',
    myRewards: '0 DBP',
    totalStaked: '81.895 AAVE',
    apr: 'N/A%',
    walletBalance: '0 AAVE',
  },
  {
    id: 11,
    icon: '/static/images/pool/srm.png',
    title: 'SRM Pool',
    myStake: '0 SRM',
    myRewards: '0 DBP',
    totalStaked: '109275.552 SRM',
    apr: 'N/A%',
    walletBalance: '0 SRM',
  },
  {
    id: 12,
    icon: '/static/images/pool/tomoe.png',
    title: 'TOMOE Pool',
    myStake: '0 TOMOE',
    myRewards: '0 DBP',
    totalStaked: '269831.033 TOMOE',
    apr: 'N/A%',
    walletBalance: '0 TOMOE',
  },
]
