export const poolData = [
  {
    id: 1,
    icon: '/static/images/pool/wBNB.png',
    title: 'wBNB Pool',
    myStake: '0 wBNB',
    myRewards: '0 DBP',
    totalStaked: '823.188 wBNB',
    apr: 'N/A%',
    walletBalance: '0 wBNB',
  },
  {
    id: 2,
    icon: '/static/images/pool/BTCB.jpeg',
    title: 'BTCB Pool',
    myStake: '0 BTCB',
    myRewards: '0 DBP',
    totalStaked: '12.261 BTCB',
    apr: 'N/A%',
    walletBalance: '0 BTCB',
  },
  {
    id: 3,
    icon: '/static/images/pool/CAKE.jpeg',
    title: 'CAKE Pool',
    myStake: '0 CAKE',
    myRewards: '0 DBP',
    totalStaked: '9702.008 CAKE',
    apr: 'N/A%',
    walletBalance: '0 CAKE',
  },
  {
    id: 4,
    icon: '/static/images/pool/GRT.png',
    title: 'GRT Pool',
    myStake: '0 GRT',
    myRewards: '0 DBP',
    totalStaked: '2257.872 GRT',
    apr: 'N/A%',
    walletBalance: '0 GRT',
  },
  {
    id: 5,
    icon: '/static/images/pool/XVS.jpeg',
    title: 'XVS Pool',
    myStake: '0 XVS',
    myRewards: '0 DBP',
    totalStaked: '458197.144 XVS',
    apr: 'N/A%',
    walletBalance: '0 XVS',
  },
  {
    id: 6,
    icon: '/static/images/pool/SXP.png',
    title: 'SXP Pool',
    myStake: '0 SXP',
    myRewards: '0 DBP',
    totalStaked: '2013.835 SXP',
    apr: 'N/A%',
    walletBalance: '0 SXP',
  },
  {
    id: 7,
    icon: '/static/images/pool/SFP.jpeg',
    title: 'SFP Pool',
    myStake: '0 SFP',
    myRewards: '0 DBP',
    totalStaked: '30880.990 SFP',
    apr: 'N/A%',
    walletBalance: '0 SFP',
  },
  {
    id: 8,
    icon: '/static/images/pool/BUNNY.png',
    title: 'BUNNY Pool',
    myStake: '0 BUNNY',
    myRewards: '0 DBP',
    totalStaked: '11369.942 BUNNY',
    apr: 'N/A%',
    walletBalance: '0 BUNNY',
  },
  {
    id: 9,
    icon: '/static/images/pool/AUTO.jpeg',
    title: 'AUTO Pool',
    myStake: '0 AUTO',
    myRewards: '0 DBP',
    totalStaked: '1.589 AUTO',
    apr: 'N/A%',
    walletBalance: '0 AUTO',
  },
  {
    id: 10,
    icon: '/static/images/pool/BELT.jpeg',
    title: 'BELT Pool',
    myStake: '0 BELT',
    myRewards: '0 DBP',
    totalStaked: '81.895 BELT',
    apr: 'N/A%',
    walletBalance: '0 BELT',
  },
  {
    id: 11,
    icon: '/static/images/pool/BIFI.jpeg',
    title: 'BIFI Pool',
    myStake: '0 BIFI',
    myRewards: '0 DBP',
    totalStaked: '109275.552 BIFI',
    apr: 'N/A%',
    walletBalance: '0 BIFI',
  },
  {
    id: 12,
    icon: '/static/images/pool/EGG.jpeg',
    title: 'EGG Pool',
    myStake: '0 EGG',
    myRewards: '0 DBP',
    totalStaked: '269831.033 EGG',
    apr: 'N/A%',
    walletBalance: '0 EGG',
  },
]
