export const tAssetData = [
  {
    id: 0,
    icon: '/static/images/pool/USDT.png',
    symbol: 'tUSD',
    price: '$1.00',
    desc: 'Tracks the price of a single US Dollar (USD). This Synth always remains constant at 1.',
    fee: '0.30%',
    status: 'live',
    filter: 'crypto',
    link: 'https://kwenta.io/exchange/sUSD',
  },
  {
    id: 1,
    icon: '/static/images/pool/wBNB.png',
    symbol: 'tEUR',
    price: '$1.00',
    desc: 'Tracks the price of sEUR Euros through price feeds supplied by an oracle.',
    fee: '0.30%',
    status: 'live',
    filter: 'commodity',
    link: 'https://kwenta.io/exchange/sUSD',
  },
  {
    id: 2,
    icon: '/static/images/pool/BUSD.png',
    symbol: 'tJPY',
    price: '$1.00',
    desc: 'Tracks the price of sJPY Japanese Yen through price feeds supplied by an oracle.',
    fee: '0.30%',
    status: 'live',
    filter: 'commodity',
    link: 'https://kwenta.io/exchange/sUSD',
  },
  {
    id: 3,
    icon: '/static/images/pool/CAKE.jpeg',
    symbol: 'tUSD',
    price: '$1.00',
    desc: 'Tracks the price of a single US Dollar (USD). This Synth always remains constant at 1.',
    fee: '0.30%',
    status: 'live',
    filter: 'crypto',
    link: 'https://kwenta.io/exchange/sUSD',
  },
  {
    id: 4,
    icon: '/static/images/pool/BTCB.jpeg',
    symbol: 'tAUD',
    price: '$1.00',
    desc: 'Tracks the price of sAUD Australian Dollars through price feeds supplied by an oracle.',
    fee: '0.30%',
    status: 'pause',
    filter: 'equities',
    link: 'https://kwenta.io/exchange/sUSD',
  },
  {
    id: 5,
    icon: '/static/images/pool/ETH.png',
    symbol: 'tGBP',
    price: '$1.00',
    desc: 'Tracks the price of sGBP Pound Sterling through price feeds supplied by an oracle.',
    fee: '0.30%',
    status: 'live',
    filter: 'crypto',
    link: 'https://kwenta.io/exchange/sUSD',
  },
  {
    id: 6,
    icon: '/static/images/pool/BUNNY.png',
    symbol: 'tCHF',
    price: '$1.00',
    desc: 'Tracks the price of sCHF Swiss Franc through price feeds supplied by an oracle.',
    fee: '0.30%',
    status: 'live',
    filter: 'forex',
    link: 'https://kwenta.io/exchange/sUSD',
  },
  {
    id: 7,
    icon: '/static/images/pool/XVS.jpeg',
    symbol: 'tKRW',
    price: '$1.00',
    desc: 'Tracks the price of sKRW South Korean Won through price feeds supplied by an oracle.',
    fee: '0.30%',
    status: 'live',
    filter: 'equities',
    link: 'https://kwenta.io/exchange/sUSD',
  },
  {
    id: 8,
    icon: '/static/images/pool/USDC.png',
    symbol: 'tXAU',
    price: '$1.00',
    desc: 'Tracks the price of sXAU Gold Ounce through price feeds supplied by an oracle.',
    fee: '0.30%',
    status: 'live',
    filter: 'equities',
    link: 'https://kwenta.io/exchange/sUSD',
  },
  {
    id: 9,
    icon: '/static/images/pool/DAI.png',
    symbol: 'tXAG',
    price: '$1.00',
    desc: 'Tracks the price of sXAG Silver Ounce through price feeds supplied by an oracle.',
    fee: '0.30%',
    status: 'live',
    filter: 'crypto',
    link: 'https://kwenta.io/exchange/sUSD',
  },
  {
    id: 10,
    icon: '/static/images/pool/DOT.png',
    symbol: 'tOIL',
    price: '$1.00',
    desc: 'Tracks the price of sOIL Perpetual Oil Futures through price feeds supplied by an oracle.',
    fee: '0.30%',
    status: 'frozen',
    filter: 'commodity',
    link: 'https://kwenta.io/exchange/sUSD',
  },
  {
    id: 11,
    icon: '/static/images/pool/USDT.png',
    symbol: 'tBTC',
    price: '$1.00',
    desc: 'Tracks the price of sBTC Bitcoin through price feeds supplied by an oracle.',
    fee: '0.30%',
    status: 'frozen',
    filter: 'forex',
    link: 'https://kwenta.io/exchange/sUSD',
  },
];
