export const tAssetData = [
  {
    id: 1,
    icon: '/static/images/crypto/tBTC.png',
    symbol: 'tBTC',
    price: '$36,776',
    desc: 'Tracks the price of tBTC Bitcoin through price feeds supplied by an oracle.',
    fee: '0.30%',
    status: 'onboarding',
    filter: 'crypto',
    link: 'https://kwenta.io/exchange/sUSD',
  },
  {
    id: 2,
    icon: '/static/images/pool/ETH.png',
    symbol: 'tETH',
    price: '$2,601.73',
    desc: 'Tracks the price of tETH Ether through price feeds supplied by an oracle.',
    fee: '0.30%',
    status: 'onboarding',
    filter: 'crypto',
    link: 'https://kwenta.io/exchange/sUSD',
  },
  {
    id: 3,
    icon: '/static/images/crypto/tLINK.png',
    symbol: 'tLINK',
    price: '$28.31',
    desc: 'Tracks the price of tLINK Chainlink through price feeds supplied by an oracle.',
    fee: '0.30%',
    status: 'onboarding',
    filter: 'crypto',
    link: 'https://kwenta.io/exchange/sUSD',
  },
  {
    id: 4,
    icon: '/static/images/crypto/tDASH.png',
    symbol: 'tDASH',
    price: '$185.04',
    desc: 'Tracks the price of tDASH Dash through price feeds supplied by an oracle.',
    fee: '0.30%',
    status: 'onboarding',
    filter: 'crypto',
    link: 'https://kwenta.io/exchange/sUSD',
  },
  {
    id: 5,
    icon: '/static/images/crypto/tXMR.png',
    symbol: 'tXMR',
    price: '$275.54',
    desc: 'Tracks the price of tXMR Monero through price feeds supplied by an oracle.',
    fee: '0.30%',
    status: 'onboarding',
    filter: 'crypto',
    link: 'https://kwenta.io/exchange/sUSD',
  },
  {
    id: 6,
    icon: '/static/images/forex/tCNY.svg',
    symbol: 'tCNY',
    price: '$0.16',
    desc: 'Tracks the price of tCNY Chinese Yuan through price feeds supplied by an oracle.',
    fee: '0.30%',
    status: 'onboarding',
    filter: 'forex',
    link: 'https://kwenta.io/exchange/sUSD',
  },
  {
    id: 7,
    icon: '/static/images/forex/tJPY.png',
    symbol: 'tJPY',
    price: '$0.0091',
    desc: 'Tracks the price of tJPY Japanese Yen through price feeds supplied by an oracle.',
    fee: '0.30%',
    status: 'onboarding',
    filter: 'forex',
    link: 'https://kwenta.io/exchange/sUSD',
  },
  {
    id: 8,
    icon: '/static/images/forex/tAUD.png',
    symbol: 'tAUD',
    price: '$0.77',
    desc: 'Tracks the price of tAUD Australian Dollars through price feeds supplied by an oracle.',
    fee: '0.30%',
    status: 'onboarding',
    filter: 'forex',
    link: 'https://kwenta.io/exchange/sUSD',
  },
  {
    id: 9,
    icon: '/static/images/forex/tCHF.png',
    symbol: 'tCHF',
    price: '$1.11',
    desc: 'Tracks the price of tCHF Swiss Franc through price feeds supplied by an oracle.',
    fee: '0.30%',
    status: 'onboarding',
    filter: 'forex',
    link: 'https://kwenta.io/exchange/sUSD',
  },
  {
    id: 10,
    icon: '/static/images/equities/tFB.png',
    symbol: 'tFB',
    price: '$328.94',
    desc: 'Tracks the price of tFB Facebook through price feeds supplied by an oracle.',
    fee: '0.30%',
    status: 'onboarding',
    filter: 'equities',
    link: 'https://kwenta.io/exchange/sUSD',
  },
  {
    id: 11,
    icon: '/static/images/equities/tAMZN.png',
    symbol: 'tAMZN',
    price: '$3,300.65',
    desc: 'Tracks the price of tAMZN Amazon through price feeds supplied by an oracle.',
    fee: '0.30%',
    status: 'onboarding',
    filter: 'equities',
    link: 'https://kwenta.io/exchange/sUSD',
  },
  {
    id: 12,
    icon: '/static/images/equities/tAAPL.svg',
    symbol: 'tAAPL',
    price: '$123.49',
    desc: 'Tracks the price of tAAPL Apple through price feeds supplied by an oracle.',
    fee: '0.30%',
    status: 'onboarding',
    filter: 'equities',
    link: 'https://kwenta.io/exchange/sUSD',
  },
  {
    id: 13,
    icon: '/static/images/equities/tNFLX.png',
    symbol: 'tNFLX',
    price: '$494.44',
    desc: 'Tracks the price of tNFLX Netflix through price feeds supplied by an oracle.',
    fee: '0.30%',
    status: 'onboarding',
    filter: 'equities',
    link: 'https://kwenta.io/exchange/sUSD',
  },
  {
    id: 14,
    icon: '/static/images/equities/tGOOGL.png',
    symbol: 'tGOOGL',
    price: '$2,344.14',
    desc: 'Tracks the price of tGOOGL Alphabet through price feeds supplied by an oracle.',
    fee: '0.30%',
    status: 'onboarding',
    filter: 'equities',
    link: 'https://kwenta.io/exchange/sUSD',
  },
  {
    id: 15,
    icon: '/static/images/equities/tAMC.png',
    symbol: 'tAMC',
    price: '$58.02',
    desc: 'Tracks the price of tAMC Anonymous Coin through price feeds supplied by an oracle.',
    fee: '0.30%',
    status: 'onboarding',
    filter: 'equities',
    link: 'https://kwenta.io/exchange/sUSD',
  },
  {
    id: 16,
    icon: '/static/images/equities/tCOIN.svg',
    symbol: 'tCOIN',
    price: '$234.57',
    desc: 'Tracks the price of tCOIN Coinbase through price feeds supplied by an oracle.',
    fee: '0.30%',
    status: 'onboarding',
    filter: 'equities',
    link: 'https://kwenta.io/exchange/sUSD',
  },
  {
    id: 17,
    icon: '/static/images/equities/tTSLA.svg',
    symbol: 'tTSLA',
    price: '$576.85',
    desc: 'Tracks the price of tTSLA Tesla through price feeds supplied by an oracle.',
    fee: '0.30%',
    status: 'onboarding',
    filter: 'equities',
    link: 'https://kwenta.io/exchange/sUSD',
  },
  {
    id: 18,
    icon: '/static/images/equities/tBABA.jpeg',
    symbol: 'tBABA',
    price: '$216.55',
    desc: 'Tracks the price of tBABA Alibaba through price feeds supplied by an oracle.',
    fee: '0.30%',
    status: 'onboarding',
    filter: 'equities',
    link: 'https://kwenta.io/exchange/sUSD',
  },
  {
    id: 19,
    icon: '/static/images/commodity/tOIL.png',
    symbol: 'tOIL',
    price: '$68.99',
    desc: 'Tracks the price of tOIL Perpetual Oil Futures through price feeds supplied by an oracle.',
    fee: '0.30%',
    status: 'onboarding',
    filter: 'commodity',
    link: 'https://kwenta.io/exchange/sUSD',
  },
  {
    id: 20,
    icon: '/static/images/commodity/tGOLD.PNg',
    symbol: 'tGOLD',
    price: '$1,873.50',
    desc: 'Tracks the price of tGOLD Gold Ounce through price feeds supplied by an oracle.',
    fee: '0.30%',
    status: 'onboarding',
    filter: 'commodity',
    link: 'https://kwenta.io/exchange/sUSD',
  },
  {
    id: 21,
    icon: '/static/images/commodity/tSILVER.webp',
    symbol: 'tSILVER',
    price: '$27.3783',
    desc: 'Tracks the price of tSILVER Silver Ounce through price feeds supplied by an oracle.',
    fee: '0.30%',
    status: 'onboarding',
    filter: 'commodity',
    link: 'https://kwenta.io/exchange/sUSD',
  },
];
